config/routes.rb
Rails.application.routes.draw do
  get "payments/new"
  get "payments/create"
  get "teachers/index"
  get "teachers/destroy"
  resources :classrooms, only: [ :index, :show ]

  resources :payments, only: [ :new, :create ] do
  collection do
    get "success", to: "payments#success"
    get "cancel", to: "payments#cancel"
  end
  end
  resources :classrooms do
    collection do
      get "by_grade/:grade", to: "classrooms#by_grade", as: "by_grade"
    end
    member do
      get :grading
      get :grade_level
    end
    resources :students, only: [ :index, :show ]
  end

  get "/students/scan", to: "admin#scan_qr"
  resources :attendances
  resources :students do
    collection do
      post "mark_attendance"
    end
  end

  get "home/index"
  resource :session
  resources :passwords, param: :token
  resources :signup, only: %i[new create]
  resources :users, only: %i[index] do
    member do
      patch :approve
      delete :cancel
    end
  end

get "login", to: "sessions#new", as: "login"

  get "/admin/scan_qr", to: "admin#scan_qr"
  post "/admin/checkin", to: "admin#checkin"
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
  resources :students do
    member do
      patch :toggle_status
      patch :archive
      patch :activate
    end
    collection do
      get :manage  # This will map to students#manage
    end
  end
  get "classrooms/:id/grades/:grade", to: "classrooms#grading", as: :grading_by_grade
  get "grades/:grade", to: "classrooms#by_grade", as: :grade



  resources :teachers, only: [ :index, :destroy ]
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  allow_unauthenticated_access only: %i[new create]

  def new
    @user = User.new
  end

  def create
    ActiveRecord::Base.transaction do
      @user = User.new(user_params)

      if @user.save
        if @user.approved?
          start_new_session_for @user
          redirect_to after_authentication_url
        else
          flash[:notice] = "Your account is pending approval. Please wait for admin approval."
          redirect_to login_path
        end
      else
        render :new, status: :unprocessable_entity
      end
    end
  rescue ActiveRecord::RecordInvalid => e
    flash[:alert] = "Error: #{e.message}"
    render :new
  end

  private

  def user_params
    permitted = params.require(:user).permit(:first_name, :last_name, :personal_email, :password, :password_confirmation, :school_id)
    role = params[:user][:role].to_s
    permitted[:role] = %w[teacher admin].include?(role) ? role : "teacher"
    permitted
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/new.html.erb
<%= render "shared/single_box" do %>
  <h1 class="text-3xl font-bold text-center pb-4">
    <%= render "shared/logo_text" %> Sign Up
  </h1>

  <% if @user.errors.any? %>
    <div class="alert alert-error mt-4">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, url: signup_index_path, class: "form-control mt-4", local: true, html: { autocomplete: "on" }) do |form| %>
    <%= form.text_field :first_name, class: "input input-bordered w-full mt-2", placeholder: "First Name", required: true %>
    <%= form.text_field :last_name, class: "input input-bordered w-full mt-2", placeholder: "Last Name", required: true %>

    <%= form.email_field :personal_email, class: "input input-bordered w-full mt-2", placeholder: "Your Personal Email", required: true %>

    <%= form.password_field :password, class: "input input-bordered w-full mt-2", placeholder: "Password", required: true, autocomplete: "new-password" %>
    <%= form.password_field :password_confirmation, class: "input input-bordered w-full mt-2", placeholder: "Confirm Password", required: true, autocomplete: "new-password" %>
    <%= form.select :school_id, School.all.collect { |s| [s.name, s.id] }, { prompt: "Select School" }, class: "input input-bordered w-full mt-2" %>

    <div class="mt-4">
      <div class="flex items-center mt-2">
        <%= form.radio_button :role, "teacher", class: "radio radio-primary" %>
        <div class="ml-2 px-2">Teacher</div>
        <%= form.radio_button :role, "student", class: "radio radio-primary" %>
        <div class="ml-2 px-2">Student</div>
      </div>
    </div>

    <%= form.submit "Sign Up", class: "btn btn-primary w-full mt-4" %>
  <% end %>

  <div class="text-center py-4">
    or
  </div>
  <div>
    <%= link_to "Sign in", new_session_path, method: :get, class: "btn btn-secondary btn-wide w-full" %>
  </div>
<% end %>